[package]
name = "buffman_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
slab = "0.4.11"

[dev-dependencies]
rand = "0.9.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
rand_xoshiro = "0.7.0"
